org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dandroid.user.home=C:/AndroidUserHome -Duser.home=C:/AndroidUserHome -Dgradle.user.home=C:/AndroidUserHome/.gradle
android.useAndroidX=true
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
systemProp.android.user.home=C\:/AndroidUserHome
systemProp.user.home=C\:/AndroidUserHome
systemProp.gradle.user.home=C\:/AndroidUserHome/.gradle
