// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrevGCNQ_yr20Sak7yiRACcHpJxKYgUGo',
    appId: '1:84361764950:web:36d9d8e29b2e32eceb9bf7',
    messagingSenderId: '84361764950',
    projectId: 'ai-work-planner-846fe',
    authDomain: 'ai-work-planner-846fe.firebaseapp.com',
    storageBucket: 'ai-work-planner-846fe.firebasestorage.app',
    measurementId: 'G-EJ4DYSB546',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbYFR1neJpb3D43wtBGJOhjofRy9fBCq8',
    appId: '1:84361764950:android:3a00de8490b469b6eb9bf7',
    messagingSenderId: '84361764950',
    projectId: 'ai-work-planner-846fe',
    storageBucket: 'ai-work-planner-846fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARxaCcH14onO7dN-6JjiM5PRV06I66Q2k',
    appId: '1:84361764950:ios:1221bcdedc0bc91beb9bf7',
    messagingSenderId: '84361764950',
    projectId: 'ai-work-planner-846fe',
    storageBucket: 'ai-work-planner-846fe.firebasestorage.app',
    iosBundleId: 'com.example.aiWorkPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARxaCcH14onO7dN-6JjiM5PRV06I66Q2k',
    appId: '1:84361764950:ios:1221bcdedc0bc91beb9bf7',
    messagingSenderId: '84361764950',
    projectId: 'ai-work-planner-846fe',
    storageBucket: 'ai-work-planner-846fe.firebasestorage.app',
    iosBundleId: 'com.example.aiWorkPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrevGCNQ_yr20Sak7yiRACcHpJxKYgUGo',
    appId: '1:84361764950:web:9eb9e63d86da395eeb9bf7',
    messagingSenderId: '84361764950',
    projectId: 'ai-work-planner-846fe',
    authDomain: 'ai-work-planner-846fe.firebaseapp.com',
    storageBucket: 'ai-work-planner-846fe.firebasestorage.app',
    measurementId: 'G-F50WCQGPBK',
  );
}
